# Generated by Django 2.0.7 on 2018-07-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180719_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='message',
            field=models.TextField(default='', max_length=30000),
        ),
    ]
