# Generated by Django 2.0.7 on 2018-07-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180719_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
