# Generated by Django 2.0.7 on 2018-07-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categorie',
            new_name='category',
        ),
    ]
